// =================================================================
// Sprint Reporting Dashboard
// Portfolio-ready statistics and analytics script
// =================================================================

// =================================================================
// Configuration
// =================================================================

const REPORT_SHEET_NAME = 'Sprint Analytics';
const ROW_PADDING_AFTER_CHART = 2;

// Expected sprint sheet columns.
// Header matching is case-insensitive and ignores extra spaces.
const COL_NAME_DEVELOPER = 'Developer';
const COL_NAME_BACKLOG = 'Backlog';
const COL_NAME_PROJECT = 'Project';
const COL_NAME_STATUS = 'Status';

// Status values generated by backend logic.
const STATUS_SOLVED = 'Solved';
const STATUS_UNSOLVED = 'Unsolved';

// Backlog values.
// If Backlog is "Yes", the task is treated as unsolved.
// If Backlog is "No" or empty, the task is treated as solved.
const BACKLOG_YES = 'yes';
const BACKLOG_NO = 'no';

// =================================================================
// Menu
// =================================================================

function onOpen() {
  SpreadsheetApp
    .getUi()
    .createMenu('📊 Sprint Analytics')
    .addItem(
      'Generate Analytics Report',
      'runFullStatisticsUpdate'
    )
    .addToUi();
}

// =================================================================
// Main entry point
// =================================================================

function runFullStatisticsUpdate() {
  const ui = SpreadsheetApp.getUi();

  try {
    const activeSpreadsheet =
      SpreadsheetApp.getActiveSpreadsheet();

    const sprintSheets =
      getSprintSheets(activeSpreadsheet);

    if (sprintSheets.length === 0) {
      ui.alert(
        'No sprint sheets found using format "dd.mm-dd.mm". ' +
        'Analytics report was not generated.'
      );
      return;
    }

    // Backend-controlled status update.
    // This replaces locale-dependent spreadsheet formulas.
    sprintSheets.forEach(sheet => {
      updateTaskStatuses(sheet);
    });

    const latestSprintSheet =
      sprintSheets[sprintSheets.length - 1];

    ui.showSidebar(
      HtmlService
        .createHtmlOutput(
          '<p>Collecting and processing sprint data...</p>'
        )
        .setTitle('Status')
    );

    const {
      overallStats,
      latestSprintDeveloperStats,
      latestSprintProjectStats
    } =
      collectDataFromSprints(
        sprintSheets,
        latestSprintSheet
      );

    const reportSheet =
      getAndPrepareSheet(
        activeSpreadsheet,
        REPORT_SHEET_NAME
      );

    let currentRow = 1;

    currentRow =
      generateOverallDeveloperReport(
        reportSheet,
        overallStats,
        currentRow
      );

    currentRow =
      generateLatestSprintDeveloperReport(
        reportSheet,
        latestSprintDeveloperStats,
        latestSprintSheet.getName(),
        currentRow
      );

    currentRow =
      generateLatestSprintProjectReport(
        reportSheet,
        latestSprintProjectStats,
        latestSprintSheet.getName(),
        currentRow
      );

    SpreadsheetApp.flush();

    ui.showSidebar(
      HtmlService
        .createHtmlOutput(
          '<p>Done! Analytics report updated.</p>' +
          '<script>setTimeout(google.script.host.close, 3000);</script>'
        )
        .setTitle('Status')
    );

  } catch (err) {
    ui.alert(
      'Critical error while generating analytics report: ' +
      err.message
    );

    Logger.log(
      'Critical analytics error: ' +
      err.message +
      '\nStack: ' +
      err.stack
    );
  }
}

// =================================================================
// Sheet preparation
// =================================================================

function getAndPrepareSheet(spreadsheet, sheetName) {
  let sheet =
    spreadsheet.getSheetByName(sheetName);

  if (sheet) {
    sheet.clear();

    sheet
      .getCharts()
      .forEach(chart => sheet.removeChart(chart));

  } else {
    sheet =
      spreadsheet.insertSheet(sheetName);
  }

  return sheet;
}

// =================================================================
// Sprint sheet discovery
// =================================================================

function getSprintSheets(spreadsheet) {
  const sprintSheetRegex =
    /^\d{2}\.\d{2}-\d{2}\.\d{2}$/;

  const today = new Date();
  const currentYear = today.getFullYear();
  const currentMonth = today.getMonth() + 1;

  return spreadsheet
    .getSheets()
    .filter(sheet =>
      sprintSheetRegex.test(sheet.getName())
    )
    .sort((a, b) => {
      const dateA =
        parseSprintStartDate_(
          a.getName(),
          sprintSheetRegex,
          currentYear,
          currentMonth
        );

      const dateB =
        parseSprintStartDate_(
          b.getName(),
          sprintSheetRegex,
          currentYear,
          currentMonth
        );

      return dateA.getTime() - dateB.getTime();
    });
}

function parseSprintStartDate_(
  sheetName,
  sprintSheetRegex,
  currentYear,
  currentMonth
) {
  const match =
    sheetName.match(sprintSheetRegex);

  const startDay =
    parseInt(match[1], 10);

  const startMonth =
    parseInt(match[2], 10);

  let sprintYear = currentYear;

  // If it is early in the current year and the sprint starts
  // in November or December, treat it as a previous-year sprint.
  if (
    currentMonth <= 2 &&
    startMonth >= 11
  ) {
    sprintYear = currentYear - 1;
  }

  return new Date(
    sprintYear,
    startMonth - 1,
    startDay
  );
}

// =================================================================
// Backend status calculation
// =================================================================

function updateTaskStatuses(sheet) {
  const values =
    sheet
      .getDataRange()
      .getValues();

  if (values.length <= 1) {
    return;
  }

  const headers =
    normalizeHeaders_(values[0]);

  const backlogCol =
    headers.indexOf(
      normalizeHeader_(COL_NAME_BACKLOG)
    );

  const statusCol =
    headers.indexOf(
      normalizeHeader_(COL_NAME_STATUS)
    );

  if (
    backlogCol === -1 ||
    statusCol === -1
  ) {
    const missingColumns = [];

    if (backlogCol === -1) {
      missingColumns.push(COL_NAME_BACKLOG);
    }

    if (statusCol === -1) {
      missingColumns.push(COL_NAME_STATUS);
    }

    throw new Error(
      'Missing required columns on sheet "' +
      sheet.getName() +
      '": ' +
      missingColumns.join(', ')
    );
  }

  const statusValues = [];

  for (let i = 1; i < values.length; i++) {
    const row = values[i];

    const backlog =
      row[backlogCol] === null ||
      row[backlogCol] === undefined
        ? ''
        : String(row[backlogCol])
            .trim()
            .toLowerCase();

    const status =
      backlog === BACKLOG_YES
        ? STATUS_UNSOLVED
        : STATUS_SOLVED;

    statusValues.push([status]);
  }

  sheet
    .getRange(
      2,
      statusCol + 1,
      statusValues.length,
      1
    )
    .setValues(statusValues);
}

// =================================================================
// Data collection
// =================================================================

function collectDataFromSprints(
  sprintSheets,
  latestSprintSheet
) {
  const overallStats = {};
  const latestSprintDeveloperStats = {};
  const latestSprintProjectStats = {};

  sprintSheets.forEach(sheet => {
    const isLatestSprint =
      sheet.getName() === latestSprintSheet.getName();

    const range =
      sheet.getDataRange();

    if (range.getNumRows() <= 1) {
      return;
    }

    const values =
      range.getValues();

    const headers =
      normalizeHeaders_(values[0]);

    const developerCol =
      headers.indexOf(
        normalizeHeader_(COL_NAME_DEVELOPER)
      );

    const statusCol =
      headers.indexOf(
        normalizeHeader_(COL_NAME_STATUS)
      );

    const projectCol =
      headers.indexOf(
        normalizeHeader_(COL_NAME_PROJECT)
      );

    if (
      developerCol === -1 ||
      statusCol === -1 ||
      projectCol === -1
    ) {
      const missingColumns = [];

      if (developerCol === -1) {
        missingColumns.push(COL_NAME_DEVELOPER);
      }

      if (statusCol === -1) {
        missingColumns.push(COL_NAME_STATUS);
      }

      if (projectCol === -1) {
        missingColumns.push(COL_NAME_PROJECT);
      }

      throw new Error(
        'Missing required columns on sheet "' +
        sheet.getName() +
        '": ' +
        missingColumns.join(', ')
      );
    }

    for (let i = 1; i < values.length; i++) {
      const row = values[i];

      const developer =
        row[developerCol]
          ? String(row[developerCol]).trim()
          : '';

      const status =
        row[statusCol]
          ? String(row[statusCol]).trim()
          : '';

      if (!developer) {
        continue;
      }

      if (!overallStats[developer]) {
        overallStats[developer] = {
          solved: 0,
          unsolved: 0
        };
      }

      applyStatusCount_(
        overallStats[developer],
        status
      );

      if (isLatestSprint) {
        if (!latestSprintDeveloperStats[developer]) {
          latestSprintDeveloperStats[developer] = {
            solved: 0,
            unsolved: 0
          };
        }

        applyStatusCount_(
          latestSprintDeveloperStats[developer],
          status
        );

        const project =
          row[projectCol]
            ? String(row[projectCol]).trim()
            : 'No Project';

        if (!latestSprintProjectStats[project]) {
          latestSprintProjectStats[project] = {
            solved: 0,
            unsolved: 0
          };
        }

        applyStatusCount_(
          latestSprintProjectStats[project],
          status
        );
      }
    }
  });

  return {
    overallStats,
    latestSprintDeveloperStats,
    latestSprintProjectStats
  };
}

function applyStatusCount_(stats, status) {
  if (status === STATUS_SOLVED) {
    stats.solved++;
  } else if (status === STATUS_UNSOLVED) {
    stats.unsolved++;
  }
}

// =================================================================
// Report generation
// =================================================================

function generateOverallDeveloperReport(
  sheet,
  stats,
  startRow
) {
  const tableData =
    [['Developer', 'Solved', 'Unsolved']];

  for (const developer in stats) {
    tableData.push([
      developer,
      stats[developer].solved,
      stats[developer].unsolved
    ]);
  }

  sheet
    .getRange(startRow, 1)
    .setValue(
      'OVERALL DEVELOPER STATISTICS (ALL SPRINTS)'
    )
    .setFontWeight('bold');

  startRow++;

  if (tableData.length <= 1) {
    sheet
      .getRange(startRow, 1)
      .setValue('No data to display.')
      .setFontStyle('italic');

    return startRow + 2;
  }

  const dataRange =
    sheet.getRange(
      startRow,
      1,
      tableData.length,
      tableData[0].length
    );

  dataRange.setValues(tableData);
  sheet.setColumnWidth(1, 250);

  const chartHeightInRows = 18;

  const chart =
    sheet
      .newChart()
      .asColumnChart()
      .addRange(dataRange)
      .setMergeStrategy(
        Charts.ChartMergeStrategy.MERGE_COLUMNS
      )
      .setNumHeaders(1)
      .setOption(
        'title',
        'Tasks by Developer (All Sprints)'
      )
      .setOption('isStacked', false)
      .setOption('legend', { position: 'top' })
      .setPosition(startRow, 5, 0, 0)
      .build();

  sheet.insertChart(chart);

  return startRow +
    chartHeightInRows +
    ROW_PADDING_AFTER_CHART;
}

function generateLatestSprintDeveloperReport(
  sheet,
  stats,
  sprintName,
  startRow
) {
  const tableData =
    [['Developer', 'Solved', 'Unsolved']];

  for (const developer in stats) {
    tableData.push([
      developer,
      stats[developer].solved,
      stats[developer].unsolved
    ]);
  }

  sheet
    .getRange(startRow, 1)
    .setValue(
      'DEVELOPER STATISTICS (SPRINT ' +
      sprintName +
      ')'
    )
    .setFontWeight('bold');

  startRow++;

  if (tableData.length <= 1) {
    sheet
      .getRange(startRow, 1)
      .setValue('No data to display.')
      .setFontStyle('italic');

    return startRow + 2;
  }

  const dataRange =
    sheet.getRange(
      startRow,
      1,
      tableData.length,
      tableData[0].length
    );

  dataRange.setValues(tableData);

  const chartHeightInRows = 18;

  const chart =
    sheet
      .newChart()
      .asColumnChart()
      .addRange(dataRange)
      .setMergeStrategy(
        Charts.ChartMergeStrategy.MERGE_COLUMNS
      )
      .setNumHeaders(1)
      .setOption(
        'title',
        'Tasks by Developer in Sprint ' +
        sprintName
      )
      .setOption('isStacked', false)
      .setOption('legend', { position: 'top' })
      .setPosition(startRow, 5, 0, 0)
      .build();

  sheet.insertChart(chart);

  return startRow +
    chartHeightInRows +
    ROW_PADDING_AFTER_CHART;
}

function generateLatestSprintProjectReport(
  sheet,
  stats,
  sprintName,
  startRow
) {
  const tableData =
    [['Project', 'Solved', 'Unsolved']];

  for (const project in stats) {
    tableData.push([
      project,
      stats[project].solved,
      stats[project].unsolved
    ]);
  }

  sheet
    .getRange(startRow, 1)
    .setValue(
      'PROJECT STATISTICS (SPRINT ' +
      sprintName +
      ')'
    )
    .setFontWeight('bold');

  startRow++;

  if (tableData.length <= 1) {
    sheet
      .getRange(startRow, 1)
      .setValue('No data to display.')
      .setFontStyle('italic');

    return startRow + 2;
  }

  const dataRange =
    sheet.getRange(
      startRow,
      1,
      tableData.length,
      tableData[0].length
    );

  dataRange.setValues(tableData);

  const chartHeightInRows = 18;

  const chart =
    sheet
      .newChart()
      .asColumnChart()
      .addRange(dataRange)
      .setMergeStrategy(
        Charts.ChartMergeStrategy.MERGE_COLUMNS
      )
      .setNumHeaders(1)
      .setOption(
        'title',
        'Tasks by Project in Sprint ' +
        sprintName
      )
      .setOption('isStacked', false)
      .setOption('legend', { position: 'top' })
      .setPosition(startRow, 5, 0, 0)
      .build();

  sheet.insertChart(chart);

  return startRow +
    chartHeightInRows +
    ROW_PADDING_AFTER_CHART;
}

// =================================================================
// Utility helpers
// =================================================================

function normalizeHeaders_(headers) {
  return headers.map(header =>
    normalizeHeader_(header)
  );
}

function normalizeHeader_(header) {
  return String(header)
    .toLowerCase()
    .replace(/[\s\u00A0]+/g, ' ')
    .trim();
}
